---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: zookeeper
    hostname: zookeeper
    image: idealista/zookeeper:latest
    pre_build_image: true
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    groups:
      - zookeeper_group
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr-network

  - name: solrcloud1
    hostname: solrcloud1
    image: ${DOCKER_IMAGE_BASE:-idealista/jdk:11.0.16-bullseye-openjdk-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    groups:
      - solrcloud
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr-network
        aliases:
          - solrcloud1
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8983:8983/tcp

  - name: solrcloud2
    hostname: solrcloud2
    image: ${DOCKER_IMAGE_BASE:-idealista/jdk:11.0.16-bullseye-openjdk-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    groups:
      - solrcloud
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr-network
        aliases:
          - solrcloud2
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8984:8983/tcp
  - name: solr-minio1
    image: minio/minio
    command: 'server /data --console-address ":9001"'
    privileged: false
    pre_build_image: true
    env:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
      MINIO_REGION: eu-west-1
    exposed_ports:
      - 9000/tcp
      - 9001/tcp
    published_ports:
      - 0.0.0.0:9000:9000
      - 0.0.0.0:9001:9001
    networks:
      - name: solr-network
        aliases:
          - solr-minio1
        links:
          - zookeeper:zookeeper
    purge_networks: true
provisioner:
  name: ansible
verifier:
  name: ansible
  directory: ./tests
